# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f62d0dcb4154600cb8fdd2037f8ab6c8d9ea39918dc6e2de5162f5f6486403cb2dad24db7c8eb51b25a85a8c54c4ca006de31f9f5849256c2d4155492279ab

test:
  secret_key_base: 0fed12d1cc78b7d66e8839a9f4c12aa3aa0f149ad16e65b246d892fc7ab532e68d9a0b58a71ab87251f9f535dc94eb27babfac8f7356286432923fd6105c1a66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
